<?php
/**
 * Created by PhpStorm.
 * User: author lihq1403 <lihaiqing1994@163.com>
 * Date: 2018/10/12
 * Time: 10:15
 */

namespace app\common\exception;

use app\common\traits\ApiReturn;
use Exception;
use Firebase\JWT\BeforeValidException;
use Firebase\JWT\ExpiredException;
use Firebase\JWT\SignatureInvalidException;
use think\exception\Handle;
use think\exception\RouteNotFoundException;

class Http extends Handle
{
    use ApiReturn;

    public function render(Exception $e)
    {
        //普通异常
        if ($e instanceof CommonException) {
            return $this->exitResponse($e->getCode(), $e->getMessage());
        }

        // 未登录
        if ($e instanceof UnauthorizedHttpException) {
            $this->exitResponse($e->getCode(), $e->getMessage());
        }

        //JWT解码出错
        if ($e instanceof SignatureInvalidException || $e instanceof ExpiredException) {
            $this->exitResponse(401, '用户未登录');
        }
        if ($e instanceof BeforeValidException) {
            $this->exitResponse(401, '签名在某个时间点之后才能用');
        }

        //无权限异常
        if ($e instanceof ForbiddenException) {
            $this->exitResponse(403, $e->getMessage());
        }

        //路由找不到
        if ($e instanceof RouteNotFoundException) {
            $this->exitResponse(404, '路由不存在');
        }

        //全局异常捕获
        if ($e instanceof \Exception) {
            //做一下记录,保留一天，方便查找
            $this->exitResponse(500, $this->systemErrorMessage($e->getMessage()));
        }

        return parent::render($e); // TODO: Change the autogenerated stub
    }

    /**
     * 生成环境仅报错服务器繁忙
     * @param $message
     * @return string
     * @author lihq1403 <lihaiqing1994@163.com>
     */
    public function systemErrorMessage($message)
    {
        if (config('app_debug') == false) {
            $message = '服务器繁忙';
        }
        return $message;
    }
}
