server {
    listen       80 reuseport;
    server_name  _;
    index index.html index.htm index.php default.html default.htm default.php;
    root  /home/wwwroot/web/hello_project/dist;

    location / {
            try_files $uri /index.html;
            access_log off;
    }

    #后端接口配置
    location ~ /(api|uploads|fixed)/ {
        proxy_pass http://127.0.0.1:8080; # 把 /api 路径下的请求转发给真正的后端服务器
        proxy_set_header Host $http_host;  # 把host头传过去，后端服务程序将收到your.domain.name，否则收到的是localhost:8080
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        access_log off;
    }

    location ~ .*\.(js|css)?$
    {
        expires      12h;
        access_log off;
    }

    location ~ /\.
    {
        deny all;
        access_log off;
    }

    access_log /home/wwwlogs/80_web_hello_project.log;
}
